kind: pipeline
type: docker
name: leetcoder

steps:
  - name: build
    image: alpine
    volumes:
      - name: cache
        path: /cache
    commands:
      - whoami

  - name: deploy
    image: alpine
    volumes:
      - name: cache
        path: /cache
    commands:
      - ls -al
      - docker ps

volumes:
  - name: cache
    temp: {}
