kind: pipeline
type: docker
name: leetcoder

steps:
  - name: build
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/php-composer:7.3
#    volumes:
#      - name: cache
#        path: /data/composer
    commands:
      - echo $MYSQL_HOST
      - composer install --no-dev --optimize-autoloader

  - name: deploy
    image: alpine
    commands:
      - ls -al
      - docker ps


#volumes:
#  - name: cache
#    host:
#      path: /data/composer

trigger:
  branch:
    - master
