kind: pipeline
type: docker
name: leetcoder-build

steps:
  - name: build
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/php-composer-docker:7.3
    volumes:
      - name: cache
        path: /data/composer/
    commands:
      - echo $MYSQL_HOST
      - composer install --no-dev --optimize-autoloader
      - rm -rf build
      - mkdir build
      - cp .env.example .env
      - echo $DB_PORT
      - cat .env
      - cp -r app bootstrap config database resources public routes storage vendor deploy .env composer.json composer.lock build/
      - cp deploy/* ./
      - ls -al
      - docker build -t registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder .
#      - docker login --username=$ALI_USERNAME registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder -p $ALI_PASSWORD
#      - docker push registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder
#node:
#  type: builder

volumes:
  - name: cache
    host:
      path: /data/composer/

trigger:
  branch:
    - master

---
kind: pipeline
type: docker
name: leetcoder-deploy

steps:
  - name: deploy
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/docker-compose
    commands:
      - ls
      - docker ps
#      - docker-compose up -d

trigger:
  branch:
    - master
