kind: pipeline
type: docker
name: leetcoder

steps:
  - name: build
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/php-composer-docker:7.3
    volumes:
      - name: cache
        path: /data/composer/
    commands:
      - echo $REDIS_HOST
      - cp .env.example .env
      - sed -i "s/DB_HOST=.*/DB_HOST=$DB_HOST/g" .env
      - sed -i "s/DB_PORT=.*/DB_PORT=$DB_PORT/g" .env
      - sed -i "s/DB_USERNAME=.*/DB_USERNAME=$DB_USERNAME/g" .env
      - sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=$DB_PASSWORD/g" .env
      - sed -i "s/REDIS_HOST=.*/REDIS_HOST=$REDIS_HOST/g" .env
      - composer install --no-dev --optimize-autoloader
      - rm -rf build
      - mkdir build
      - echo $DB_PORT
      - cp -r app bootstrap config database resources public routes storage vendor deploy .env composer.json composer.lock build/
      - cp deploy/* ./
      - ls -al
      - docker build -t registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder .
      - docker login --username=$REPO_USERNAME registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder -p $REPO_PASSWORD
      - docker push registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder
    when:
      instance:
        - drone.ytlmike.com

  - name: deploy
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/docker-compose
    commands:
      - cd deploy
      - docker-compose up -d
    when:
      status:
        - success

volumes:
  - name: cache
    host:
      path: /data/composer/

trigger:
  branch:
    - master
