kind: pipeline
type: docker
name: leetcoder

steps:
  - name: build
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/php-composer-docker:7.3
    commands:
      - echo $MYSQL_HOST
      - composer install --no-dev --optimize-autoloader
    environment:
      MYSQL_HOST:
        from_secret: MYSQL_HOST
      MYSQL_USERNAME:
        from_secret: MYSQL_USERNAME
      MYSQL_PASSWORD:
          from_secret: MYSQL_PASSWORD

  - name: deploy
    image: alpine
    commands:
      - ls -al


#volumes:
#  - name: cache
#    host:
#      path: /data/composer

trigger:
  branch:
    - master
