kind: pipeline
type: docker
name: leetcoder

environment:
  GOOS: linux
  GOARCH: amd64

steps:
  - name: build
    commands:
      - echo $MYSQL_HOST
      - composer install --no-dev --optimize-autoloader

  - name: deploy
    commands:
      - ls -al
      - docker ps


#volumes:
#  - name: cache
#    host:
#      path: /data/composer

trigger:
  branch:
    - master
