kind: pipeline
type: docker
name: leetcoder

steps:
  - name: build
    image: alpine
#    volumes:
#      - name: cache
#        path: /cache
    commands:
      - mkdir cache
      - touch cache/a
      - echo '123123' >> cache/a
      - ls -al

  - name: deploy
    image: alpine
#    volumes:
#      - name: cache
#        path: /cache
    commands:
      - ls -al
      - cat cache/a
      - docker ps

volumes:
  - name: cache
    temp: {}
