kind: pipeline
type: docker
name: leetcoder

steps:
  - name: build
    commands:
      - echo $MYSQL_HOST
      - composer install --no-dev --optimize-autoloader
    environment:
      MYSQL_HOST=${MYSQL_HOST}

  - name: deploy
    commands:
      - ls -al
      - docker ps


#volumes:
#  - name: cache
#    host:
#      path: /data/composer

trigger:
  branch:
    - master
