version: '3'

services:
  leetcoder:
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder
    restart: always
    networks:
      - traefik
    volumes:
      - /data/leetcoder/storage/logs/:/var/www/leetcoder/storage/logs/
      - /data/leetcoder/public/avatar/:/var/www/leetcoder/public/avatar/
    labels:
      - "traefik.http.routers.leetcoder.rule=Host(`leetcoder.ytlmike.com`)"
      - "traefik.http.services.leetcoder.loadbalancer.server.port=80"
networks:
  traefik:
    external: true
