version: '3'

services:
  leetcoder:
    image: registry-vpc.cn-qingdao.aliyuncs.com/ytlmike/leetcoder
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.http.routers.leetcoder.rule=Host(`leetcoder.ytlmike.com`)"
      - "traefik.http.services.leetcoder.loadbalancer.server.port=80"
networks:
  traefik:
    external: true
